version: 2
updates:
  # Check for Go module updates in the root directory
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Check for GitHub Action updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Check for Docker base image updates (root Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Check for Docker base image updates (devcontainer Dockerfile)
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
