// Code generated by specforge. DO NOT EDIT.

package main

// Config is the root configuration struct.
type Config struct {
	PostgresField PostgresConfig `yaml:"postgres"`
}

type PostgresConfig struct {
	// Maximum duration in seconds a connection survives
	ConnMaxLifetimeField int `yaml:"conn_max_lifetime"`
	// Target database name
	DatabaseField string `yaml:"database"`
	// Postgres server hostname or IP address
	HostField string `yaml:"host"`
	// Maximum idle database connections in pool
	MaxIdleConnsField int `yaml:"max_idle_conns"`
	// Maximum open database connections
	MaxOpenConnsField int `yaml:"max_open_conns"`
	// Database authentication password
	PasswordField string `yaml:"password"`
	// Postgres server port number
	PortField int `yaml:"port"`
	// Number of reconnection retry attempts
	RetryAttemptsField int `yaml:"retry_attempts"`
	// Delay in milliseconds between retry attempts
	RetryBackoffMsField int `yaml:"retry_backoff_ms"`
	// SSL connection security mode
	SslModeField string `yaml:"ssl_mode"`
	// Database user name
	UserField string `yaml:"user"`
}

func (c *Config) Postgres() *PostgresConfig {
	return &c.PostgresField
}

func (n *PostgresConfig) ConnMaxLifetime() int {
	return n.ConnMaxLifetimeField
}

func (n *PostgresConfig) Database() string {
	return n.DatabaseField
}

func (n *PostgresConfig) Host() string {
	return n.HostField
}

func (n *PostgresConfig) MaxIdleConns() int {
	return n.MaxIdleConnsField
}

func (n *PostgresConfig) MaxOpenConns() int {
	return n.MaxOpenConnsField
}

func (n *PostgresConfig) Password() string {
	return n.PasswordField
}

func (n *PostgresConfig) Port() int {
	return n.PortField
}

func (n *PostgresConfig) RetryAttempts() int {
	return n.RetryAttemptsField
}

func (n *PostgresConfig) RetryBackoffMs() int {
	return n.RetryBackoffMsField
}

func (n *PostgresConfig) SslMode() string {
	return n.SslModeField
}

func (n *PostgresConfig) User() string {
	return n.UserField
}
