// Package config is the public entry point for loading, accessing,
// and managing semantic configurations generated by configforge.
//
// For complete developer reference and tutorials, please refer to the narrative
// user guide: https://github.com/SSOHEB/configforge/blob/main/docs/guide.md
//
// # Lifecycle
//
// The configuration lifecycle consists of three distinct phases:
//
//  1. Specification: Define your application configuration metadata schema
//     in a `metadata.yaml` file, listing namespaces, fields, and validation rules.
//  2. Generation: Run the `configforge generate` CLI tool to compile the specification
//     into typed Go structs (e.g. `generated_config.go`) and a JSON Schema.
//  3. Loading & Validation: In your Go application, use the loader from the
//     runtime package to parse YAML files, inject default values, apply
//     environment variables, and perform validation checks before startup.
//
// # Basic Usage
//
// Assuming your code generation has generated a configuration package for your app,
// you would load and validate configuration as follows:
//
//	package main
//
//	import (
//		"fmt"
//		"log"
//		"os"
//
//		"configforge/internal/runtime"
//		"configforge/internal/schema"
//		"configforge/internal/parser"
//		"configforge/internal/validator"
//	)
//
//	func main() {
//		// 1. Load schema AST (usually built-in or read from metadata.yaml)
//		rawMeta, err := parser.ParseFile("metadata.yaml")
//		if err != nil {
//			log.Fatalf("failed to parse spec: %v", err)
//		}
//		ast, err := schema.Build(rawMeta)
//		if err != nil {
//			log.Fatalf("failed to build AST: %v", err)
//		}
//
//		// 2. Load config, apply defaults & environment overrides
//		cfg, rawConfig, err := runtime.LoadAndPrepareFile[Config](ast, "config.yaml")
//		if err != nil {
//			log.Fatalf("failed to load config: %v", err)
//		}
//
//		// 3. Validate against constraints (e.g. min, max, enum, regex)
//		valErrs := validator.Validate(ast, rawConfig)
//		if len(valErrs) > 0 {
//			for _, e := range valErrs {
//				fmt.Fprintln(os.Stderr, e.Error())
//			}
//			log.Fatalf("invalid configuration")
//		}
//
//		// 4. Access typed values using the functional API
//		fmt.Printf("HTTP Server Port: %d\n", cfg.Instrumentation().Http().Port())
//	}
package config
