// Code generated by configforge. DO NOT EDIT.

package main

// Config is the root configuration struct.
type Config struct {
	InstrumentationField InstrumentationConfig `yaml:"instrumentation"`
}

type Http struct {
	// API key for external service integration
	ApiKeyField string `yaml:"api_key"`
	// Headers to capture
	CaptureHeadersField []string `yaml:"capture_headers"`
	// Enables HTTP instrumentation
	EnabledField bool `yaml:"enabled"`
	// HTTP server bind address
	HostField     string `yaml:"host"`
	LogLevelField string `yaml:"log_level"`
	PortField     int    `yaml:"port"`
	// Query parameters to redact from logs
	RedactQueryField []string `yaml:"redact_query"`
	// Request timeout in seconds
	TimeoutField int `yaml:"timeout"`
}

type InstrumentationConfig struct {
	HttpField Http `yaml:"http"`
}

func (c *Config) Instrumentation() *InstrumentationConfig {
	return &c.InstrumentationField
}

func (n *Http) ApiKey() string {
	return n.ApiKeyField
}

func (n *Http) CaptureHeaders() []string {
	return n.CaptureHeadersField
}

func (n *Http) Enabled() bool {
	return n.EnabledField
}

func (n *Http) Host() string {
	return n.HostField
}

func (n *Http) LogLevel() string {
	return n.LogLevelField
}

func (n *Http) Port() int {
	return n.PortField
}

func (n *Http) RedactQuery() []string {
	return n.RedactQueryField
}

func (n *Http) Timeout() int {
	return n.TimeoutField
}

func (n *InstrumentationConfig) Http() *Http {
	return &n.HttpField
}
