// Code generated by configforge. DO NOT EDIT.

package main

// Config is the root configuration struct.
type Config struct {
	Instrumentation InstrumentationConfig `yaml:"instrumentation"`
}

type Http struct {
	// API key for external service integration
	ApiKey string `yaml:"api_key"`
	// Headers to capture
	CaptureHeaders []string `yaml:"capture_headers"`
	// Enables HTTP instrumentation
	Enabled bool `yaml:"enabled"`
	// HTTP server bind address
	Host     string `yaml:"host"`
	LogLevel string `yaml:"log_level"`
	Port     int    `yaml:"port"`
	// Query parameters to redact from logs
	RedactQuery []string `yaml:"redact_query"`
	// Request timeout in seconds
	Timeout int `yaml:"timeout"`
}

type InstrumentationConfig struct {
	Http Http `yaml:"http"`
}
