// Code generated by codrao. DO NOT EDIT.

package main

// Config is the root configuration struct.
type Config struct {
	RedisField RedisConfig `yaml:"redis"`
}

type RedisConfig struct {
	// Redis logical database index
	DbField int `yaml:"db"`
	// Connection establishment timeout in seconds
	DialTimeoutField int `yaml:"dial_timeout"`
	// Redis server host name or IP address
	HostField string `yaml:"host"`
	// Optional password for authentication
	PasswordField string `yaml:"password"`
	// Maximum number of socket connections in pool
	PoolSizeField int `yaml:"pool_size"`
	// Redis server port number
	PortField int `yaml:"port"`
	// Socket read timeout in seconds
	ReadTimeoutField int `yaml:"read_timeout"`
	// List of Redis Sentinel addresses for HA configurations
	SentinelAddrsField []string `yaml:"sentinel_addrs"`
	// Enables secure TLS connection
	TlsEnabledField bool `yaml:"tls_enabled"`
	// Socket write timeout in seconds
	WriteTimeoutField int `yaml:"write_timeout"`
}

func (c *Config) Redis() *RedisConfig {
	return &c.RedisField
}

func (n *RedisConfig) Db() int {
	return n.DbField
}

func (n *RedisConfig) DialTimeout() int {
	return n.DialTimeoutField
}

func (n *RedisConfig) Host() string {
	return n.HostField
}

func (n *RedisConfig) Password() string {
	return n.PasswordField
}

func (n *RedisConfig) PoolSize() int {
	return n.PoolSizeField
}

func (n *RedisConfig) Port() int {
	return n.PortField
}

func (n *RedisConfig) ReadTimeout() int {
	return n.ReadTimeoutField
}

func (n *RedisConfig) SentinelAddrs() []string {
	return n.SentinelAddrsField
}

func (n *RedisConfig) TlsEnabled() bool {
	return n.TlsEnabledField
}

func (n *RedisConfig) WriteTimeout() int {
	return n.WriteTimeoutField
}
