package generator

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/SSOHEB/SpecForge/internal/schema"
)

// GoFormatError is returned when go/format.Source fails to format the generated source code.
type GoFormatError struct {
	Source string
	Err    error
}

func (e *GoFormatError) Error() string {
	return fmt.Sprintf("go/format.Source failed: %v\nRaw Source:\n%s", e.Err, e.Source)
}

// GenOptions defines code generation parameters.
type GenOptions struct {
	WithFunctionalAPI bool
}

// GenerateGoCode consumes the AST and produces a gofmt-formatted Go source file.
func GenerateGoCode(ast *schema.AST, packageName string, opts ...GenOptions) ([]byte, error) {
	var opt GenOptions
	if len(opts) > 0 {
		opt = opts[0]
	}

	// fieldName resolves naming collisions when the Functional API is enabled.
	// In Go, a struct cannot have a field and a method with the same name.
	// Appending "Field" to the struct field name (e.g. "PortField") frees up
	// the unsuffixed name to be used for the getter method (e.g. "Port()").
	fieldName := func(name string) string {
		if opt.WithFunctionalAPI {
			return name + "Field"
		}
		return name
	}

	if ast == nil || ast.Root == nil {
		var sb strings.Builder
		sb.WriteString("// Code generated by specforge. DO NOT EDIT.\n\n")
		sb.WriteString("package " + packageName + "\n\n")
		sb.WriteString("type Config struct {}\n")
		return format.Source([]byte(sb.String()))
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by specforge. DO NOT EDIT.\n\n")
	sb.WriteString("package " + packageName + "\n\n")

	// Write the root Config struct
	sb.WriteString("// Config is the root configuration struct.\n")
	sb.WriteString("type Config struct {\n")
	for _, f := range ast.Root.Fields {
		if f.Description != "" {
			sb.WriteString("\t// " + f.Description + "\n")
		}
		sb.WriteString(fmt.Sprintf("\t%s %s `yaml:%q`\n", fieldName(f.Name), goTypeStr(f.Type), f.YAMLKey))
	}
	for _, child := range ast.Root.Children {
		sb.WriteString(fmt.Sprintf("\t%s %s `yaml:%q`\n", fieldName(child.Name), structNameForNode(child), child.YAMLKey))
	}
	sb.WriteString("}\n\n")

	// Collect and sort all nested nodes for deterministic output
	allNodes := collectNodes(ast.Root)
	sort.Slice(allNodes, func(i, j int) bool {
		return structNameForNode(allNodes[i]) < structNameForNode(allNodes[j])
	})

	// Generate struct definitions for namespaces
	for _, node := range allNodes {
		typeName := structNameForNode(node)
		sb.WriteString(fmt.Sprintf("type %s struct {\n", typeName))
		for _, f := range node.Fields {
			if f.Description != "" {
				sb.WriteString("\t// " + f.Description + "\n")
			}
			sb.WriteString(fmt.Sprintf("\t%s %s `yaml:%q`\n", fieldName(f.Name), goTypeStr(f.Type), f.YAMLKey))
		}
		for _, child := range node.Children {
			sb.WriteString(fmt.Sprintf("\t%s %s `yaml:%q`\n", fieldName(child.Name), structNameForNode(child), child.YAMLKey))
		}
		sb.WriteString("}\n\n")
	}

	// Generate getter methods if WithFunctionalAPI is enabled
	if opt.WithFunctionalAPI {
		// Root methods
		for _, f := range ast.Root.Fields {
			sb.WriteString(fmt.Sprintf("func (c *Config) %s() %s {\n", f.Name, goTypeStr(f.Type)))
			sb.WriteString(fmt.Sprintf("\treturn c.%sField\n", f.Name))
			sb.WriteString("}\n\n")
		}
		for _, child := range ast.Root.Children {
			sb.WriteString(fmt.Sprintf("func (c *Config) %s() *%s {\n", child.Name, structNameForNode(child)))
			sb.WriteString(fmt.Sprintf("\treturn &c.%sField\n", child.Name))
			sb.WriteString("}\n\n")
		}

		// Nested node methods
		for _, node := range allNodes {
			typeName := structNameForNode(node)
			for _, f := range node.Fields {
				sb.WriteString(fmt.Sprintf("func (n *%s) %s() %s {\n", typeName, f.Name, goTypeStr(f.Type)))
				sb.WriteString(fmt.Sprintf("\treturn n.%sField\n", f.Name))
				sb.WriteString("}\n\n")
			}
			for _, child := range node.Children {
				sb.WriteString(fmt.Sprintf("func (n *%s) %s() *%s {\n", typeName, child.Name, structNameForNode(child)))
				sb.WriteString(fmt.Sprintf("\treturn &n.%sField\n", child.Name))
				sb.WriteString("}\n\n")
			}
		}
	}

	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		return nil, &GoFormatError{
			Source: sb.String(),
			Err:    err,
		}
	}

	return formatted, nil
}

func structNameForNode(n *schema.Node) string {
	if len(n.Path) == 1 {
		return n.Name + "Config"
	}
	return n.Name
}

func collectNodes(n *schema.Node) []*schema.Node {
	var list []*schema.Node
	for _, child := range n.Children {
		list = append(list, child)
		list = append(list, collectNodes(child)...)
	}
	return list
}

func goTypeStr(t schema.FieldType) string {
	switch t {
	case schema.TypeBool:
		return "bool"
	case schema.TypeString:
		return "string"
	case schema.TypeInt:
		return "int"
	case schema.TypeFloat:
		return "float64"
	case schema.TypeStringSlice:
		return "[]string"
	case schema.TypeIntSlice:
		return "[]int"
	case schema.TypeStringMap:
		return "map[string]string"
	default:
		return "any"
	}
}
