name: Verify GoReleaser

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: Install goreleaser
        run: go install github.com/goreleaser/goreleaser/v2@latest
        
      - name: Run GoReleaser Check
        run: |
          ~/go/bin/goreleaser check 2>&1 | tee goreleaser_log.txt
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add goreleaser_log.txt
          git commit -m "ci: save goreleaser log"
          git push || true
          exit $PIPESTATUS
